name: Backend CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }} ./backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }}
