name: Backend CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }} ./backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }}
