name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app || mkdir ~/app && cd ~/app
            rm -rf dream-vacation-app
            git clone https://github.com/${{ github.repository }}.git
            cd dream-vacation-app/backend
            docker build -t dream-backend .
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 5000:5000 dream-backend
