name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change this if you deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.190.13.34 >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          ssh azureuser@172.190.13.34 "cd /home/azureuser && echo 'Connected to VM!'"
