name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: azureuser
        key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
        script: |
          if [ ! -d "~/dream-vacation-app" ]; then
            git clone https://github.com/Agbaje24i/dream-vacation-app.git ~/dream-vacation-app
          else
            cd ~/dream-vacation-app && git pull origin main
          fi
          cd ~/dream-vacation-app
          npm install
          npx pm2 stop all || true
          npx pm2 start npm -- start
          npx pm2 save
