name: Deploy Dream Vacation App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-frontend ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-backend

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/dream-vacation-app
            # Stop any running containers
            docker compose down
            # Pull the latest images from Docker Hub
            docker compose pull
            # Start containers in detached mode
            docker compose up -d
            # Optional: clean unused images
            docker image prune -f

