name: Frontend CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production  # 👈 Tell GitHub to use environment secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: Check if secrets are present
        run: |
          echo "DOCKER_USERNAME = ${{ secrets.DOCKER_USERNAME }}"
          echo "TOKEN present? ${{ secrets.DOCKER_TOKEN != '' }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${{ github.sha }} ./frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${{ github.sha }}
